Authorization Token JWT
MytiX/BileMo pull request #7
Opened 2022-08-04 16:55 UTC by MytiX

2022-08-05 10:23 UTC, maitre-hibou requested changes

2022-08-05 10:23 UTC, maitre-hibou commented on src/Security/Authenticator/JWTAuthenticator.php
> +        return new JsonResponse($data, ($exception->getCode() != 0) ? $exception->getCode() : Response::HTTP_INTERNAL_SERVER_ERROR);
Ici, plutot utiliser le code  401 Unauthorized

2022-08-05 10:23 UTC, maitre-hibou commented on src/EventSubscriber/ExceptionSubscriber.php
> +<?php
Ici, on va plutot remplacer le EventSubscriber par un EventListener pour spécialiser la classe sur le seul et unique role de renvoyer les exceptions sous format json

2022-08-08 17:07 UTC, MytiX commented on src/Security/Authenticator/JWTAuthenticator.php
> +        return new JsonResponse($data, ($exception->getCode() != 0) ? $exception->getCode() : Response::HTTP_INTERNAL_SERVER_ERROR);
Patch [554a711](https://github.com/MytiX/BileMo/pull/7/commits/554a711e183db3b28bd5294f2ec9851675f2056a)

2022-08-08 17:07 UTC, MytiX commented on src/EventSubscriber/ExceptionSubscriber.php
> +<?php
Patch [554a711](https://github.com/MytiX/BileMo/pull/7/commits/554a711e183db3b28bd5294f2ec9851675f2056a)

2022-08-08 17:07 UTC, merged